import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { AuthProvider } from "@/context/AuthContext";
=======
>>>>>>> 3f76ae404c3f39c46526086138ed6acd4ec93523

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "TripNest",
  description: "Travel Planning & Trip Management Platform",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 3f76ae404c3f39c46526086138ed6acd4ec93523
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
<<<<<<< HEAD
      <body className="min-h-full flex flex-col">
        <AuthProvider>{children}</AuthProvider>
      </body>
=======
      <body className="min-h-full flex flex-col">{children}</body>
>>>>>>> 3f76ae404c3f39c46526086138ed6acd4ec93523
    </html>
  );
}
